### ISSUE TITLE
Проблема с админкой

### ISSUE THREAD

**Issue by 69leo** [zerolabnet/ultimate-antifilter#2]
Приветствую! Что-то у меня , после установки, в админку не заходит по порту 9090

docker-pr 1333            root    4u  IPv4  10027      0t0  TCP *:9090 (LISTEN)
docker-pr 1339            root    4u  IPv6  10035      0t0  TCP *:9090 (LISTEN)

tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      1333/docker-proxy   

Не видит порт из локалки.  Меня адрес 0 0.0.0.0:9090 смущаект, разве он не на 127.0.0.1 слушать должен?

**Comment by zerolabnet** [comment]
Так запускали? 

```
docker run -d \
--name ultimate-antifilter \
--restart=unless-stopped \
-p 9090:8080/tcp \
zerolabnet/ultimate-antifilter:latest
```

Недостаточно информации. При таком запуске проблем не будет. Внутри контейнера nginx висит на порту 8080.
